-- MySQL Script generated by MySQL Workbench
-- Wed Mar 30 20:48:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba` (
  `idOsoba` INT NOT NULL,
  `Prijmeni` VARCHAR(45) NOT NULL,
  `Jmeno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOsoba`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`certifikat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`certifikat` (
  `idcertifikate` INT NOT NULL,
  `klic` VARCHAR(45) NOT NULL,
  `datum platnosti` DATE NOT NULL,
  `Osoba_idOsoba` INT NOT NULL,
  PRIMARY KEY (`idcertifikate`),
  INDEX `fk_certifikate_Osoba_idx` (`Osoba_idOsoba` ASC) VISIBLE,
  CONSTRAINT `fk_certifikate_Osoba`
    FOREIGN KEY (`Osoba_idOsoba`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
